
 const SOCKET_EVENTS = {
    JOIN_CHAT:'CONNECT',
    LOG_OFF:'DISCONNECT',
    BROADCAST:'BROADCAST',
}

 const USER_EVENT = {
    IS_SUPER_USER_AVAILABLE:'IS_SUPER_USER_AVAILABLE',
    SET_SUPER_USER:'SET_SUPER_USER',
    AVAILABLE_USER:'AVAILABLE_USER',
    EXIT:'SUPER_USER_EXIT',
    SUPER_USER_IS_AVAILABLE:'SUPER_USER_IS_AVAILABLE',
    SUPER_USER_SET:'SUPER_USER_SET',
    PUSH_POST:'PUSH_POST'
}

 const USER_TYPE ={
    SUPER_USER:'SUPER_USER',
    USER:'USER',
}

module.exports={SOCKET_EVENTS,USER_EVENT,USER_TYPE}